name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: CookBookSocial/frontend
        run: npm install

      - name: Build project
        working-directory: CookBookSocial/frontend
        run: npm run build
